version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: mysql:5.7.25
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: meteorshower_test

    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Setup MySQL
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

            apt update -qq
            apt install mysql-client -y -qq
            ./scripts/setup_mysql.sh
      - run:
          name: Test
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
