version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: mysql:5.7.25
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: meteorshower_test
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Checkout submodule
          command: |
            git submodule update --init
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Setup MySQL
          command: |
            sudo apt update -qq
            sudo apt install mysql-client -y -qq

            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
            ./scripts/setup_mysql.sh
      - run:
          name: Test
          command: ./gradlew test
      - run:
          name: Build
          command: |
            ./gradlew clean :app:assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Deployment
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              ./.circleci/setup-heroku.sh
              ./.circleci/setup-retry.sh

              retry -- heroku plugins:install java
              retry -- heroku deploy:jar \
                --jar app/build/libs/app.jar --jdk 11 --app pinemz-meteorshower
            fi
